oidc_providers:
  - name: Discord
    client_id: 
    client_secret: 
    redirect_uri: 
      - http://pusher.workadventure.localhost/third-party-login/discord/callback

  # Exemple for Google

  # - name: Google
  #   client_id: YOUR_GOOGLE_CLIENT_ID
  #   client_secret: YOUR_GOOGLE_CLIENT_SECRET
  #   redirect_uri: YOUR_GOOGLE_REDIRECT_URI


# Add more OIDC providers if needed